GET http://localhost:3000/products
###
POST http://localhost:3000/products
Content-Type: application/json

{
    "image_url": "https://images.immediate.co.uk/production/volatile/sites/30/2020/02/Glass-and-bottle-of-milk-fe0997a.jpg?quality=90&resize=960,872",
    "title": "Test",
    "description": "Test",
    "price": "80"
}