GET http://localhost:3000/products
###
GET http://localhost:3000/totalproducts
###
POST http://localhost:3000/products
Content-Type: application/json

{
    "image_url": "Test url",
    "title": "Test",
    "description": "Test",
    "price": "80"
}
###
DELETE http://localhost:3000/products/46
###